version: '3.8'
services:
  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opefrvtms
  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker-init:artemis.2.28.0
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - ./artemis:/var/lib/artemis-instance
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
      - AMQ_USER=admin
      - AMQ_PASSWORD=admin
  ignite:
    image: apacheignite/ignite:2.14.0-jdk11
    mem_reservation: 2048m
    ports:
      - "10800:10800"
      - "47500:47500"
    volumes:
      - ./ignite:/opt/ignite/work
    environment:
      - CONFIG_URI=/opt/ignite/work/ignite-config/ignite-config-tms.xml
  cassandra:
    image: filipmorrys/cassandra-trigger-elastic:windows
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra:/var/lib/cassandra
  elasticsearch:
    image: elasticsearch:7.17.16
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=tmstmm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
  cloudconfig:
    image: filipmorrys/cloudconfig-tms:6.0.0-tms-windows
    ports:
      - "8888:8888"
    volumes:
      - ../irl-configuration-develop:/opt/cloudconfig
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 2s
      retries: 10
  topologycachemng:
    image: filipmorrys/topologycachemng-tms:1.0.10-windows
    restart: always
    ports:
      - "9090:9090"
    environment:
        - SPRING_PROFILES_ACTIVE=podman
        - SPRING_CLOUD_CONFIG_URI=http://cloudconfig:8888
    depends_on:
      cloudconfig:
        condition: service_healthy
#  notificationmng:
#    image: artifactory.mova.indra.es/docker-opefrv/copefrvh60/tms-infra-server-notificationmanager:6.0.3-SNAPHOT
#    ports:
#      - "9083:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=podman
#      - SPRING_CLOUD_CONFIG_URI=http://cloudconfig:8888

volumes:
  pgdata: