version: '3.8'
services:
  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=opefrvtms
  artemis:
    image: amusarra/apache-artemis:2.16.0
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - ./artemis:/var/lib/artemis-instance
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
  ignite:
    image: apacheignite/ignite:2.14.0
    platform: linux/amd64
    mem_reservation: 2048m
    ports:
      - "10800:10800"
      - "47500:47500"
    volumes:
      - ./ignite:/opt/ignite/work
  cassandra:
#    image: cassandra:4.0.1
    image: cassandra-trigger-elastic:latest
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra:/var/lib/cassandra
  elasticsearch:
    image: elasticsearch:7.17.16
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=tmstmm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  cloudconfig:
    image: cloudconfig-tms:v1
    ports:
      - "8888:8888"
    volumes:
      - ../tms-configuration:/opt/cloudconfig
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 5
  topologycachemng:
    image: topologycachemng-tms:1.0.9-SNAPSHOT
    restart: always
    ports:
      - "9090:9090"
#    depends_on:
#      cloudconfig:
#        condition: service_healthy
#    links:
#      - cloudconfig
